env:
  global:
    - secure: LDlyzcVwHuMw1+tTj3k7cT9tAnNX8UewLnKBVgceAJXxWN2aR+BasKZRj+ORvfaLe/4LycniWfgC/BdYSMX1GEqn4oxE1bgDdObr1A4qbgEZzYYpdfOfMBwXamLVRLkNA8Dyniom1EBrCNWrHM2ISULsz+0f1/yCMNu4epWm3siHFoeF44o6QZfTyUurf3FnvHpySWlu7d3dkHMDOEn8flVnq/oYnCacpm9HjdSFEj0OqIMUPY5+k4Jh2dg7k4VtDpMU3bm+WguzOJemvQ2fgxt/o74QXFSOQvT/At2NCFhp2dPYf3x/6iW1B51vqq+ewweRCFSiyzlnCNbbkAbfnrIGrqlpIV5N1MvJkpB1xxef1DG9P+QUEc2d9hM5eMPDvJoPTMHEPxKiVz/fDOicBoFUib44C+LG4fS37lcvHscCh/RpmMMyJsq0PxAsJ6KmyrdBbVyVl2E+W3KDYII1a3YkgLfedoIM7tqv9Pxh2otx4KHMKxVN4aui2Ow91AUPopAbF55M+tVhVvf1UxSLxCKWhUMTiYSg3PbqlJutGSUvdKPBSzUv1cqhbemNVUve8Z5y3zY0B4Yu88n1mGxpGVs8whaWB3pxBxbyh2GB5OwleCzEyUbpU9hQXLpe35SHjuL3wxsNDnDeV5Ah4vffZnulUoM4NZCU8VAIwCvaLcE=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/Basic-tracking-list_web_disconnect.me
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
