env:
  global:
    - secure: pxlGC9nLNA8duV8A4rNxRVBb3+N4rm7mv6JtZEnsVnPF6lwq8keZWojco98L3ia90A6dw+PnGJf45UbmG3RIPIEsuO2DrdxPBW2yHwpDQ7NnGy64X58kipBIkUFPDYqWbzEfhuLj2F9OxS2BPB9JFvUw5VU7ittRclpYYS1TVyiECxeod3fP5HhwA+w4BQk+Hw+Aam16JOjzY0dzk5qpiNMGE+kjyFq1mHcfSnhdvhq7kOSLSrnUi8Mg42V/hukc1KN8B+ipxXOT75vM5siKuaA4wHWyL671OW81utsR48VhiZTyovC1p7ehKW9ikDy1Fug+KgulTd58HcbOojyPv6wLe/qp3eoit81Br2CWcMxsCFzAoAj3YrGFzGLYjUu+w6FG1LUB/F23JcCP02H2t7AqxDK/z0tsnoOyaaAguD/jPIQLaV+8G/Vx8FmLrn/fxoOqHZKWYS84OlN9iQE0LD82Y7YUF9narrYNR5p03g1q0tMKSwnxvN4uYaQhb4Z2WDxjY/dzJB4K9HflfKtfB35Iv8t9N0xLCx2X13J78PP7mRSrK0Yw9CKYtnSPhFAcamZRUIzDJ6Uo7oYD6HvDTmD5grOssdzxf8Av/f6/ydc6XKGT5DiVMC+vF/QqxsOkD06PGxuj5mrMUDBXnGqOtuvRo2CgwqWQzpZEUAJCym0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/Basic-tracking-list_web_disconnect.me
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
