env:
  global:
    - secure: mdh5ttFDQrDNPsOUf5FzjXebO6szwA3OEC14qPkmVdFD+4ai0myHDXHF+BuQVG+r3UNmf6324E1d5zpRq5Z4q/vyQvLJOyHC7wJY52laHOcwRXW1PS8JVaucyHRLXxvpm6azeqibWVKM7JsJDND+g2Fm+fm3eC5D33zH3XVN3zWOGUtn15URYy/49a5PSL0BULmlV+N+n/3RZ2ZnYExTn7A4LckTOefB9bDTbwFOZWfuZsMfFxd61ftKbnq7zyrl8PLpj6MH2KxRrWwLk3UxpOORsFJkt3LaIReXOa9eVpSXXMBfOLWah/Oao3aPRPNtAh0EZzRyj8mfuGIcO86x3h0hU+uM3Qp/1COZPiKcim32GONizr5vvP29pzLgdxWDb6jwZtXIVtlbdXXvznYJ7QfKULv3aR6g8RQYXarzaJsE6/Xtdll3WgRcjlqVoXSbAE0BdZ2f3ol8VN0jR6evg5jVtTetA/8dy5X3EBszfwZSLXeXuMitmbqu9b993nNnB78ouOnkxoAcQUi7mIys7Qfode1YSYzGfXub7gkxKKv2otGXosUzzVo3x104EyVuglDdDGxTYGI51Ljq+yq2JUsAtfzxPi16V2eS2gi0v7NKzQ9RD/2LaWXPvzXQye+MdU/n+IUJBkVzETzEigXg1d/tJAUMLPVf/Q8B5sywHFo=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/Basic-tracking-list_web_disconnect.me
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
