env:
  global:
    - secure: YRsiPPNZtbSM4PcPayjpphccFsz4cHuVXvQ/f9QWgOnwXJGDccf56/KgYeOdKmUBWQGiVsz31/MougumajD1gLBljCfGrmQ+yBOryeiUfAsRm4Aw6siiXaoUqD8r7CfbY9RxnqPG3Vy6E3ockLvz9PZog/g4esLK/8aeYJpknCodZ/rBNA/Om8Raj+Tp9wkYOADkp23gctu0J8+/KsMe66Ed3KJPTPJhurydeG+bjvZrRsj23O2BJtI8/E4ibRpo7QJnCn0NiugI6scNq8TOUuKOO3HJpwI60+VrmTRAuxYjvAAlOja5GCrd+g/I2ohHS7D31BDxPSNPiw772MCP+jXONr2VdDKMZ9MMuFoRZNRDt3Pw76/C+WCkWEMPj9fGoJZZpw+8x6SFpLCwGxHGGnYM1pABfSmcT7FtCL+hu5Utf5M6vTyQLS28UFoJLYg04tZSKec9uWbdfknGidReCX1kH8b+ZWBGfc8aNZIFLCEKR1arZNWi6L/CPcMXmAKdK836GpSEs7CdR8bv0GNr4XbUYk7TwFOILE9nR1y+LjXUCK7OThSSiSU+tM5k6v5hiMOs5uFABbc1O2yJtDKfuQ0v0WpRkkefxBO/xWOWYy+ZWrHran94dIlWO5POBYipY+U3P8jAzC9FNl0/t6kw92Whubo37qghnV14QVNtpjU=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/Basic-tracking-list_web_disconnect.me
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
