env:
  global:
    - secure: PZQbu8jkCgOI4n3nGT6lhErSrp6Vf1gftJtXyi15+25qgy/z2fal2gVkttwkECiZwiH7ds20FLOYFxgbFyCSixmd0XC0LBONA5u+WhTuFrM+/FdvKYmIzbzo5ektxTdjz8qFpcb3b/dY2mqw9lUkvaTAR20U3o3zKmiJZk/7daAiVSmw2XPhPw+wyJLg7zZZrvD0ZeapePkDnzwiibfTHnpFG3a/6bkmsNkUBlCD137zQkBQr1CrFXmB2WOUxwrKdp8fT9eMJBP1HRcIrfzSfD9TmPH9XY51Q6qVoDUlX5x1UnduJ0EspIlaTK4/dGvtPyPX6ynM0sgkjJSuFa/ZjPNUwlqzvh55Pq80Zrnn6oo0DegRnNj00NrDnxyUmXpfK2L3vmp+zMnfagbnfIq0g3Tl68G58q7VzOhYoJip7jE04RD7tKxfIjwH0tVWY3o1WYILpMkm6MKi2LDbja504kwPG5VMhDVj1UQDmNgcoM59rw+yoMTAIZl57VkiU28NsCEFuyY9iedtasJu8GzrBdSx8qryppwpYcXdST8xs7xtHSWlq2y4Q31olNlhFEPM9+QBQIetRI+gEB/HW+21tqFbHDNtJP5+BLHj+Rc7RBhXOrC6B8s1gNu0lRybYd8YF+9pdyiTybi3ThBzZEfA95fZDtZfCfRzJ62lnkRNXzA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/Basic-tracking-list_web_disconnect.me
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
