env:
  global:
    - secure: YsadbqDa8uOLQ5JIUFpbyI9P58I6mewyNNqQLeN0fj8B7gnIZMYcWyJWry41TFPk8JU7VYD+rggbAKhaYL0SD0nj496Lz69SalI1prgdhOd9IGCDlyHxTtq3GcC07pWb1J36Iu+kp3hDoM5iU7YWHON4r3c+uDFMdeyLCAf4gkBHijxisym0VBdLVBZxHPQK/QUENovZ+3Pi7pf0iffojzMfcnd067KYuOIo4UU3LIC13JvdWl37NcRybhbPGFToHL13lMMijMb/4lN1uUwkVbgmRQRoW6nOVWCpqe7yJkn74JI4xYTdZO3cwxJXu6ONuceNZ31eKYYOM372+ug4kEMO3GqxJxecE0ObUX3UKvKzN0+Pi2oXR9tcOzrk28aGl6jNnxyneZcufJedObYNXDLr973imDK68gStuL3Qgi03KwlR489TSeAjYXmGTPn5pYSvdBELVJi36QVdtG4tvUa1NNdZ63Kg92oLMSMY54KsQq/q6HJZ8MwSCQb54ZFpPjDPpNvDyl6C6JiZl9VvAcHFPJUBW/VuRpvmiZk5AplXdwIjcEwoQpyKcaAD9mTLVLw72fFANArnXYmus8gWS0+JlJE4yuG/q5Mrzyp/xLEvul4ClGWWDlmDHe9SolmuRivRUstBOVKTua3SRp920hz5SsKyUYEvNmGtQ0LmjL8=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/Basic-tracking-list_web_disconnect.me
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
