env:
  global:
    - secure: cjgDWR019PrvxZtfj42NiD8JVuBebHprqlX3AbMqfRKpIcMPChJ0PACmY4cb248rGWyAJ0fABoCU5FlIn5T5LhOWLuQeJJPbDGNH+DY4qx7qVK+VVZSeKcERLIDaimGYlcd4osq9KvqUcWbidpz539EPrDnFh59zQ7uhyGbgpJvOMUWBJgL5C18oK7vZ0nyVsQJbcl4RGknlLgbbxjaekeMKMM5JnMssKcn9+S1CFq/ikulvHWy8+GdCZFKa/FxtCveUuxBCHAkp25xVY4/cQomOnwMa5/TaLOi7idnW8b07VnHv6gCi0fu8hDVY6OBdhRCE0QOpYI4jY/kDXfC6M7N8cADtcEadkDvTQCn8AsjL3qknML0xUUrv7CREdM2Bw6rOkumtXhlDk+OGwMqjp0cCyF4jeYcn1sLWBJKcm6SyoqqhpQsL91wILsF3uUefe0E3JZS9imLxM+xaazehtTTZbR3Pg+cgGTWmvFwRvjhrkjEI9b+qt8Rngu/73zyGq66ypoXF0A0UnNZ8ER8lFNAQh1wh2R2K5A96c9QSpjMCKUCYyhvl79xzifG2v+vIPeqycPVD7O4RMnu4TNHAIzFbRPIZWMTPxPIMI7hWm6wONbGox4mKWJU3YufCNW3KW6bMXqU/RIdDoTCL37f/76F79XpzBhMG8nDyYQYtw/o=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/Basic-tracking-list_web_disconnect.me
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
