env:
  global:
    - secure: Vk9FN3TjkDhQgMeLa54FDnkAf4iZwHn63eib+rjHr1V9Ec2tWR4oKnWemCjVGpSQW1TOI8kIxk9g0Vr6m1kMJu+nLR/h4/Z2x35Jsu3XSN0FGHhti0YTaeV2WbTtbQLna5qAoSrQslSTvLVVBtbDUUi1OJfebcUHM3TDhWqoLhAUCCrtIFkeHQxfr1DoxGZRvyze6+2HGPTbSoMToaLq6ipRorkkJP4OVa+U97l85o3gfgOpdrI7p/RKwoK6ls0+n6G7O5cq8yJuqCd0uifu8WHBt9yPZizrvzfycLmKIjrh4ej8IwauOPzwLE+o1/tCHWVOMs0bV80F85NKvsm+kgtqh+3utrV4+FvHGQYw140lD+daYWmbZdFKE/E/nSo3MxG4B1J5ORO5tAahUTVg4nM+x622gSK+HZdO+lBlbyuslMlGDMlkPTb+wqroXTuJxNES9iBGYW4I0eaAdKSdculWzfvlOCgDprOrPDLPbqPBTCkr8zeM3ecouehf4cS/U2OG+sIjvS4ngplqXJ0x71Eu761fWjdilcloUQVag5iJsE8nZ91ldt6MXFrmzy45REBQygRmWgazZx1RQSjandPR2f/ZXKfJfaQl1B2/t+5iDiM7xx3phGOsAcpyhEd1MA2NHgOUSt/CJrqln4lxzNpyz/CRfR/R7zvBwykdYR4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/Basic-tracking-list_web_disconnect.me
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
