env:
  global:
    - secure: p0bVslYgH5YePA91XryAbWi+SpKemjQ+hfDr9hsIJzL2OsOPa7blLJhtwMUv/S6iFt2PRaG4Uau+aNjVrMdKt5xYUZ6nWSdeZihHE4fsdwg/Tc5uTPDyJitK+jDpUxX1mGxpgaUEmI2IZSF6iTJ2tt2uV4XeKVGveA0B+o6igFwrhmZDZYsiLLrhvSSrNPGS7NNe2TyWrLv7iqE5mK76EqhxKAP4nf8J8AS6gbo8wY+W2sOcuB06nvREKyECnIp2O/v1DD5K53PUll7hEp70gK6arqlZJAy0wP/pJNiV6ExkdpneW7E68gcBprZiv26BJQKNJpO+bjAO9LfjOS1gpOlMUecP+0TGiED3kZwh+4DvxvnmK38jh+yl881ilzjLzYgGm7YNu0t94XnkbT8STfSHwTHLRP61QYk13XMff67jOeMgLiF9V3sDEmDY2SNkOoEUQglkxsdBE6hQudrF7J7I4gBt/sDcsTTW2/KxQt7cFP7PA4NBz9kPBbKTZq9cOa0SaaRHMgyjkUhnmKH+IQl2tk5KY55oyVZeamhpALnTuB94RP6IARHTXs91e+fwkBNCbCSn93Cm+zzVSIb+whqxuYsVful3gQF8Hm4owefN5fIcFXUqWUnJRIvPDo1QWMzWLo1U4qlVx0LEv6hXf3u2Ip1Ys+DJDkZ6wBSYtOc=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/Basic-tracking-list_web_disconnect.me
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
