env:
  global:
    - secure: SDZM4Ukaf8Gd2HccBoXtB/pUTo7DdX2sNTaCnBahLhlpE4xPYX0MOby+IrjuwMc90blqxuLsv+mbo/WgN+Fc8yGXW5OorrmTb9F8kYe2HOXmCy+ELMzG3yfuTHfQ2XdaTM63k9HWg5ldUCAzHnpbxs1L38a1nrBXfZHoK+Przyf2D0QPnV4KmklUDjv5t2XmZLwkm8g45GPfcmuToV0ewV+WFoKAmd+TvTG11B8TGN8C++aTM29X6oq9prTV4NtJAA0koYEnXJ5qLd87/cn5U73OjM+qyXpqQKJotEcLfyL5dbwwvaI7ZFrTLtIHqybWszf6eqGpkuhY9hN9dCpJNQjCow8RA0kShMNecTvC2Jm3Dgk/plwbFHnhKUGsVW6AIbE5x3ZkC3CaLLBhFgzcg3HtBCWE2z30Z8iaDPwYgfHsd2Nk9g9auDHsR4X/wLCws7LFF+C54g/qr2LYrVXernryJpgtQxkLaO/cMCaMCWDwV3eVyvb0PU8RpdwrH6jqLoyDLGi6WbkCTUVLfCmVBRCCfKkV2OaFaLsJP5OZ77Xp194s+Pb+nIBBI8ZLw97MWzKlkIaRS4CZWnzLKXdrMMUzD12xKdkHVn4XboZRFSFndF26uBhYJRdMBaaPqJSj52FixiM5CSmjhxW0SmX0/EiH0kVgVrg1f/41gLvStYc=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/Basic-tracking-list_web_disconnect.me
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - sudo apt-get -y install dos2unix
  - pip3 install colorama

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
