env:
  global:
    - secure: WsPj+O2daP8/NqJti26LglrJ6r1+9r4MyrW4Cf82gtUBDUUtiWKhWac8MVN9TN48k0wqdptz5U0xAIXTl0kLgRQUwcW4M45HVkjWbKjiXtA7DORbLVx60ABLQqr9ZqMqhdn97HPBflsHfCkxP3olgK8p5MtT+LNavdZ5EiMcPBnVjlDeiOfSUEkLtzwHq+uair+jeBVbvtPYgFwIElsSxkRu8vRl3KIhZsXDXCP8i9/CYwA9LMmvOxgU5uScYNeX0I/Csh0VUDxycTcsgNfPv0itgyCNyOvkr8qO6lNURT+OV2nv0y60nty9JaQCb28XqGUmeRZvp8g7GpiyBWWETwXAQJDv0+05ZOY5HG+Bzvm62xjwzHLlHtioa22/Q0wjQz+lIdEeqflsFWeb82bT04kccnAiIPkHHT0WnHghhmrrmsv14NEiMaUKLYwmN6m9okpcrCfJPPUghAMfcO4hZKH8vff+05MCWSwQgUcEN8hPgEsJUdhzmrzFr+SOxa9Im8+iHkOCW0Cg4fFnJXGrnmuS74iTiWSEztVO0x/2UCy2wYNC9sHC1hJYm5/Su/QOph4RmPRza/oR5uxu7+5tnx42NBwTWzvyBtxmR/XyQE5VBkrF61FSVcYAUHkVLnO8IhMqP1EhEB7CgmfOP74rj7MydH3bV7wV8VQWpGP8Xis=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/Basic-tracking-list_web_disconnect.me
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
