env:
  global:
    - secure: pS37aJrZQ4Vvcy2iJJEMBoPiCabXMsvWnod+L/ixouKwVKFzdWOPByXi1eSnWGM3d7wY+fGXXF9G1Vtu29opno53yL3Nfclr2jYGuPxhLuooP0sZAsy1T5i9Vqpj/N0duNSH3mbz1nEYFS1DRtOFhpOWwNYOb6nL4At7UOaLloQWjcs01gmTeiB7PPA6fjfNuypvNKKYzebtuyVNn/Y1jQX4eHCw3qXibTjuLZEgLYVETCy44E5+N9msp0sF5nvUAaPiiIvSVmXUMJ9g3+f8iisz5JsrYLe+IossnvynpZGzHPeshXIG6EsciC8g73UzIdZ580tioc8qjwoVO4KWML77uwnYYFMDexXxtt+Rb4ZftTC1POAYMtFkASt8ZrCMp0WmZY9BeYCDYDE5LvAMPbQcN7s4hvnaQR4KdHf7ABG9Q3RHEEucQBvNlxhUO60xphtnvMOs42fuSZR91ig423VGwi626o6+Ff45k/yqZxBM/1TDytlhC1zGTqb2hpPylCGQ+/d74HKC4BJzPLGsI0sMMTSDzrpeHFonR6jq+h2PuIgq++TnpRjTzmDagAahTyQMvV6v2bdfpnk/48AZoMvt51GB3dE2zT7DuZq/BFCyeWpiC7OeE1uNDzJlXczFZNjZNVKY2qwZIgB7BKgZ95i2lo/nSiT+ODkF05L7hTQ=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/Basic-tracking-list_web_disconnect.me
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
